name: build-website
run-name: ${{ github.actor }} is building the website
on: [push]
jobs:
  build-the-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: 1.10.1.693
      - name: Build Website
        run: clojure -X:build
      - name: Push Generated Website
        run: |
          git commit -am "Automatic Site Generation"
          git push