name: build-website
run-name: ${{ github.actor }} is building the website
on: [push]
jobs:
  build-the-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: 1.10.1.693
      - name: Build Website
        run: clojure -X:build
      - name: Push Generated Website
        run: |
          git config --global user.email "no-reply@no-reply.example.com"
          git config --global user.name "GitHub Actions"
          git add docs/*.html
          git commit -m "Automatic Site Generation"
          git push